"use client";

import { useState } from "react";
import { Send, Sparkles } from "lucide-react";

import { api, ApiError } from "@/lib/api";
import { useDataset } from "@/lib/dataset-context";
import type { ChatResponse } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/states";

const SUGGESTIONS = [
  "Why did ratings fall?",
  "What are customers complaining about most?",
  "Which products have the most negative reviews?",
  "What should we fix first?",
];

interface Turn {
  question: string;
  response: ChatResponse;
}

export default function InvestigatorPage() {
  const { datasetId } = useDataset();
  const [question, setQuestion] = useState("");
  const [turns, setTurns] = useState<Turn[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function ask(q: string) {
    if (!datasetId || !q.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const response = await api.chat(datasetId, q);
      setTurns((prev) => [...prev, { question: q, response }]);
      setQuestion("");
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Failed to get an answer");
    } finally {
      setLoading(false);
    }
  }

  if (!datasetId) return <EmptyState title="No dataset selected" />;

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-6">
      <div className="flex items-center gap-2">
        <Sparkles className="h-6 w-6" />
        <h1 className="text-2xl font-semibold">AI Investigator</h1>
      </div>

      {turns.length === 0 && (
        <div className="flex flex-wrap gap-2">
          {SUGGESTIONS.map((s) => (
            <button
              key={s}
              onClick={() => ask(s)}
              className="rounded-full border border-border bg-card px-3 py-1.5 text-xs hover:bg-muted"
            >
              {s}
            </button>
          ))}
        </div>
      )}

      <div className="flex flex-col gap-4">
        {turns.map((turn, i) => (
          <div key={i} className="flex flex-col gap-2">
            <div className="self-end rounded-lg bg-primary px-4 py-2 text-sm text-white">
              {turn.question}
            </div>
            <Card>
              <p className="text-sm">{turn.response.answer}</p>
              {turn.response.metrics.length > 0 && (
                <div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">
                  {turn.response.metrics.map((m) => (
                    <span key={m.label}>
                      <strong className="text-foreground">{m.value}</strong> {m.label}
                    </span>
                  ))}
                </div>
              )}
              {turn.response.incident_ids.length > 0 && (
                <p className="mt-2 text-xs text-muted-foreground">
                  Cited incidents: {turn.response.incident_ids.join(", ")}
                </p>
              )}
              <p className="mt-2 text-xs text-muted-foreground">
                Generated by: {turn.response.generated_by}
              </p>
            </Card>
          </div>
        ))}
      </div>

      {error && <p className="text-sm text-critical">{error}</p>}

      <form
        onSubmit={(e) => {
          e.preventDefault();
          ask(question);
        }}
        className="flex gap-2"
      >
        <input
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="Ask about your customers…"
          className="flex-1 rounded-lg border border-border bg-background px-3 py-2 text-sm"
        />
        <Button type="submit" disabled={loading || !question.trim()}>
          <Send className="h-4 w-4" />
          {loading ? "Thinking…" : "Ask"}
        </Button>
      </form>
    </div>
  );
}
